#!/bin/bash


#################################################
### save values for later in a file like this ###
#################################################

## Repo Name ##
REPODEF=""

## Repo Owner ##
OWNERDEF=""

## You ##
USERDEF=""

## Output directory ##
OUTDIRDEF="dist/"

## BitBucket: Your git password to this repo ##
TOKENDEF=""

## Host defaults ##
HOSTDEF="BitBucket"
BRANCHDEF="master"
TYPE="zip"  # BitBucket default is zip for git archive!
