#!/bin/bash


#################################################
### save values for later in a file like this ###
#################################################

## Repo Name ##
REPODEF=""

## Repo Owner ##
OWNERDEF=""

## You ##
USERDEF=""

## GitHub: release to fetch ##
## (comment out if not fetching a release) ##
# RELDEF="v0.0.1"

## GitHub: release archive as type ##
# TYPE="tar.gz"

## Output directory ##
OUTDIRDEF="dist/"

## GitHub: Your personal api token ##
TOKENDEF=""

## Host defaults ##
HOSTDEF="GitHub"
BRANCHDEF="master"
