#!/bin/bash


NOENV="Nope!"
ENV_DEFAULT="Nope!"


## @Disclaimer
# this script may or may not be avant-garde ascii art
# possibly an "it was funnier at the time" sort of deal
# may be best suited for entertaining dinner guests
#
# a shell utility to fetch stuff behind
# github or bitbucket private repositories
#
# you can obtain a new token here:
# https://github.com/settings/tokens
#
# @Author Jess Sullivan


if [ $# -eq 0 ] ; then
  read -p "
  LeafletSync: Do you want to load values a from file?

  If so, enter one now...:[$NOENV]:  " ENV
  ENV=${ENV:-$NOENV}
  echo
else
  ENV=$1
  shift
fi

## repo name ##
REPO="RepoName"
REPODEF="<RepoName>"

## Repo Owner ##
OWNER="TheOwner"
OWNERDEF="<TheOwner>"

## You ##
USER="You"
USERDEF="<You>"

## GitHub: release to fetch ##
REL="v0.0.1"
RELDEF="v0.0.1"

## GitHub: release archive as type ##
TYPE="tar.gz"

## output directory @ remote ##
OUTDIR="dist/"
OUTDIRDEF="dist/"

## GitHub: expanded source directory ##
EXPANDDIR="./remote__source/"
EXPANDDIRDEF="./remote_source/"

## GitHub: Your personal api token ##
TOKEN="personal-api-token"
TOKENDEF="<personal-api-token>"

## BitBucket: file to fetch ##
BFILE="<FileInBitBucket>"

## Remote defaults ##
HOST="GitHub"
HOSTDEF="GitHub"
BRANCH="master"
BRANCHDEF="master"

if ! [[ ${ENV} == ${ENV_DEFAULT} ]] ; then
  source $ENV
fi


## parse: ##

trap "kill 0" EXIT

POSITIONAL=()

while [[ $# -gt 0 ]] ; do
  key="$1"
  case $key in
        -t | --token)
        if [ ${TOKEN} == "personal-api-token" ] ; then
          TOKENDEF=$2
          echo ${TOKEN}
        fi
        shift
        shift
        ;;
        -r | --repo)
          REPODEF=$2
        shift
        shift
        ;;
        -v | --version)
          RELDEF=$2
        shift
        shift
        ;;
        -u | --user)
          USERDEF=$2
        shift
        shift
        ;;
        -a | --author)
          OWNERDEF=$2
        shift
        shift
        ;;
        -o | --out)
          OUTDIRDEF=$2
        shift
        shift
        ;;
        -bu | --b-user)
          USER=$2
          HOSTDEF="BitBucket"
        shift
        shift
        ;;
        -bp | --b-pass)
          TOKEN=$2
          TOKENDEF="BitBucket"
        shift
        shift
        ;;
        -bb | --b-branch)
          BRANCH=$2
          HOSTDEF="BitBucket"
        shift
        shift
        ;;
        -bf | --b-file)
          BFILE=$2
          HOSTDEF="BitBucket"
        shift
        shift
        ;;
        *) # unknown arg
        echo -e "\n Received an unknown argument!  Exiting...\n"
        POSITIONAL+=("$1")
        exit 0
        ;;
    esac
done

## help ##

## chintz ##
chintzyDoomText () {
  echo " _                 __ _      _     _____                    ";
  echo "| |               / _| |    | |   /  ___|                   ";
  echo "| |     ___  __ _| |_| | ___| |_  \ \`--. _   _ _ __   ___  ";
  echo "| |    / _ \/ _\` |  _| |/ _ \ __|  \`--. \ | | | '_ \ / __|";
  echo "| |___|  __/ (_| | | | |  __/ |_  /\__/ / |_| | | | | (__   ";
  echo "\_____/\___|\__,_|_| |_|\___|\__| \____/ \__, |_| |_|\___|  ";
  echo " \                      _____________________/ |             ";
  echo "  \ Fetch from Github: /        α wιρ Σ ♥ |_@__Jess          ";
  echo "  /───────────────────/ "
  echo "  \ Your API Token    | -t |  --token | Required | = ${TOKENDEF}"
  echo "   | Your Handle      | -u |  --user  | Required | = ${USERDEF}"
  echo "   | Source Repo      | -r |  --repo  \ Required  \ = ${REPODEF}"
  echo "   | Repository Owner | -a |  --author \ Required  \ = ${OWNERDEF}"
  echo "   | Release Version  | -v |  --version | Required | = ${RELDEF}"
  echo "  / Output Directory  | -o |  --out    / Optional  / = ${OUTDIRDEF}"
  echo " /─────────────────────────/"
  echo " \ Fetch from BitBucket:  /                                     "
  echo "  \──────────────────────/                                   "
  echo "   \  Your Handle       / -bu  /  --b-user  / ~Required | = ${USERDEF}"
  echo "    \ Your Passhrase   / -bp  / --b-pass   / ~Required / = ${TOKENDEF}"
  echo "     \ Source Branch  / -bb  / --b-branch / ~Optional / = ${BRANCHDEF}"
  echo "      \ Source File  / -bf  / --b-file   / ~Required / = ${BFILEDEF}"
  echo "       \────────────/ "
  echo;
  }


# heh:
chintzyDoomText;

read -p " Your Handle [$USERDEF]: " USER
USER=${USER:-$USERDEF}
echo

read -p " Source Repo [$REPODEF]: " REPO
REPO=${REPO:-$REPODEF}
echo

read -p " Repo Owner [$OWNERDEF]: " OWNER
OWNER=${OWNER:-$OWNERDEF}
echo

read -p "Host: GitHub | BitBucket [$HOSTDEF]: " HOST
HOST=${HOST:-$HOSTDEF}
echo

if [[ ${HOST} == "GitHub" ]] ; then

  read -p " Your Token [$TOKENDEF]: " TOKEN
  TOKEN=${TOKEN:-$TOKENDEF}
  echo

  read -p " Release to fetch: [$RELDEF]: " REL
  REL=${REL:-$RELDEF}
  echo

  read -p " Output to fetch (e.g. /dist/*): [$OUTDIRDEF]: " OUTDIR
  OUTDIR=${OUTDIR:-$OUTDIRDEF}
  echo

fi

if [[ ${HOST} == "BitBucket" ]] ; then

  read -p " Your Passphrase: [$TOKENDEF]: " TOKEN
  TOKEN=${TOKEN:-$TOKENDEF}
  echo

  read -p " File to Fetch: [$BFILEDEF]: "  BFILE
  BFILE=${BFILE:-$BFILEDEF}
  echo

  read -p " Source Branch: [$BRANCHDEF]: " BRANCH
  BRANCH=${BRANCH:-$BRANCHDEF}
  echo

fi

# form api call:
if [[ ${HOST} == "GitHub" ]] ; then

    ## archive filename ##
    OUTPUT="${REL}.${TYPE}"

  # check if token is not valid:
  if ! [[ ${TOKEN} =~ ^[0-9a-z]{40} ]] ; then
    SHA="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 40 | head -n 1)"
    echo -e "\nFetch from Github:\n"
    echo "Hmm, ${TOKEN} does not appear to be a valid token!"
    echo "please provide a 40 character personal GitHub API token like so:"
    echo -e "\n./LeafletSync -t ${SHA} -u you \n"
    exit 0
  fi

  # this is where we'll put the expanded source stuff:
  mkdir ${EXPANDDIR}

  COMMAND=" -u $USER:$TOKEN -o ${OUTPUT} https://codeload.github.com/${OWNER}/${REPO}/${TYPE}/${REL}?token=${TOKEN}"

  # let the user know what we're up to:
  echo -e "\n ...fetching release ${REL} from ${OWNER}/${REPO} with:\n \` ${COMMAND} \`"

else

  COMMAND=" -O -u $USER:$TOKEN https://bitbucket.org/${OWNER}/${REPO}/raw/${BRANCH}/${BFILE}"

  # let the user know what we're up to:
  echo -e "\n ...fetching file ${FILE} from ${OWNER}/${REPO} with:\n \` ${COMMAND} \`"

fi

# execute command, wait inside trap:
curl ${COMMAND}

wait

if [[ ${HOST} == "GitHub" ]] ; then

  echo -e "\n ...expanding..."

  # expand gzipped tar:
  tar -xvf ${OUTPUT} -C ${EXPANDDIR} --strip-components=1
  wait

  # copy production binary stuff from dist somewhere:
  cp -rf ${EXPANDDIR}${OUTDIR} ${OUTDIR}

  # move archive out of the way:
  mv ${OUTPUT} ${EXPANDDIR}

fi

echo -e "\n done! :) \n"
